CREATE DATABASE company;

USE company;

CREATE TABLE EMPLOYEE(
    EMPID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SALARY INT NOT NULL 
);

INSERT INTO EMPLOYEE (EMPID, NAME, SALARY)
VALUES
(203, "raj", 36550),
(204, "dev", 15000);

SELECT * FROM EMPLOYEE;