CREATE DATABASE COL;
USE COL;

CREATE TABLE SUB(
    ID INT PRIMARY KEY,
    SUB VARCHAR(50)
);

INSERT INTO SUB(ID, SUB)
VALUES
(1, 'Math'),
(2, 'Science'),
(3, 'English');

CREATE TABLE STUD(
    ROLLNO INT PRIMARY KEY,
    NAME VARCHAR(50),
    SUB_ID INT,
    MARKS INT,
    GRADE VARCHAR(50),
    CITY VARCHAR(50),
    FOREIGN KEY (SUB_ID) REFERENCES SUB(ID)
);

INSERT INTO STUD(ROLLNO, NAME, SUB_ID, MARKS, GRADE, CITY)
VALUES
(202, 'raj', 1, 96, 'A+', 'ftb'),
(210, 'raj8', 1, 45, 'A+', 'ftbk'),
(203, 'ra5j', 2, 85, 'A+', 'ftkb'),
(220, 'r5aj', 2, 81, 'A+', 'fhtb'),
(301, 'dev', 3, 79, 'B2', 'NOR');

SELECT * FROM STUD;

ALTER TABLE STUD
change NAME FULL_NAME VARCHAR(50);

DELETE FROM STUD
WHERE MARKS < 80;

ALTER TABLE STUD
DROP GRADE;

SHOW TABLES;